status of student ,apply proposal button

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -1,13 +1,16 @@
-FROM python:3.10-buster
+FROM python:3.10-alpine
 
+ARG BUILD_DEPS="gcc python3-dev musl-dev postgresql-dev jpeg-dev zlib-dev libjpeg libffi-dev openjdk8"
+RUN apk --no-cache add ${BUILD_DEPS}
+RUN pip install --upgrade pip
 RUN pip install pipenv
 
-RUN mkdir -p /app
-
-COPY . /app
-COPY Pipfile  /app/
-COPY Pipfile.lock /app/
+COPY Pipfile* ./
+RUN PIP_USER=1 PIP_IGNORE_INSTALLED=1 pipenv install --system --deploy --dev \
+    && find /usr/local \
+        \( -type d -a -name test -o -name tests \) \
+        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
+        -exec rm -rf '{}' \+ || echo "Pipenv install failed. See above for details."
 
 WORKDIR /app
-
-RUN pipenv install --system --deploy
+COPY . /app
